artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/342590679759320784/f67c58b5c1e64762aab1ad581cc21270/artifacts
end_time: null
entry_point_name: ''
experiment_id: '342590679759320784'
lifecycle_stage: active
run_id: f67c58b5c1e64762aab1ad581cc21270
run_name: secretive-robin-117
run_uuid: f67c58b5c1e64762aab1ad581cc21270
source_name: ''
source_type: 4
source_version: ''
start_time: 1746709325693
status: 1
tags: []
user_id: reema
