artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/7765d35ec2e547fbb7f4aeb11efb4b11/artifacts
end_time: 1746450494871
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: 7765d35ec2e547fbb7f4aeb11efb4b11
run_name: powerful-crab-136
run_uuid: 7765d35ec2e547fbb7f4aeb11efb4b11
source_name: ''
source_type: 4
source_version: ''
start_time: 1746450492945
status: 4
tags: []
user_id: reema
