artifact_location: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/0
creation_time: 1745329164510
experiment_id: '0'
last_update_time: 1745329164510
lifecycle_stage: active
name: Default
