artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/b20fb7abe5c4429abbef1c56cbf11dba/artifacts
end_time: 1746449113036
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: b20fb7abe5c4429abbef1c56cbf11dba
run_name: valuable-calf-871
run_uuid: b20fb7abe5c4429abbef1c56cbf11dba
source_name: ''
source_type: 4
source_version: ''
start_time: 1746449112624
status: 4
tags: []
user_id: reema
