artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/dcb65d2337a047fdac192b7fe9c8e3d6/artifacts
end_time: 1745485776056
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: dcb65d2337a047fdac192b7fe9c8e3d6
run_name: indecisive-gnat-874
run_uuid: dcb65d2337a047fdac192b7fe9c8e3d6
source_name: ''
source_type: 4
source_version: ''
start_time: 1745485761921
status: 3
tags: []
user_id: reema
