artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/cf4d06fd29be4b2bbfdaf342b19e966c/artifacts
end_time: 1745519226516
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: cf4d06fd29be4b2bbfdaf342b19e966c
run_name: grandiose-skunk-548
run_uuid: cf4d06fd29be4b2bbfdaf342b19e966c
source_name: ''
source_type: 4
source_version: ''
start_time: 1745519220554
status: 4
tags: []
user_id: reema
