artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/6cf97f7b55bf4b0f82e9d2f5fbfd46fd/artifacts
end_time: 1745441858275
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: 6cf97f7b55bf4b0f82e9d2f5fbfd46fd
run_name: puzzled-squirrel-832
run_uuid: 6cf97f7b55bf4b0f82e9d2f5fbfd46fd
source_name: ''
source_type: 4
source_version: ''
start_time: 1745441857026
status: 4
tags: []
user_id: reema
