artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/709612924041764231/4b6a6bfcaccd467299b954ce7cee9fa0/artifacts
end_time: 1746649739006
entry_point_name: ''
experiment_id: '709612924041764231'
lifecycle_stage: active
run_id: 4b6a6bfcaccd467299b954ce7cee9fa0
run_name: smiling-hound-757
run_uuid: 4b6a6bfcaccd467299b954ce7cee9fa0
source_name: ''
source_type: 4
source_version: ''
start_time: 1746649701543
status: 3
tags: []
user_id: reema
