artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/177054895211266278/eadb7132644b4d5bba45bdf5a2104b09/artifacts
end_time: null
entry_point_name: ''
experiment_id: '177054895211266278'
lifecycle_stage: active
run_id: eadb7132644b4d5bba45bdf5a2104b09
run_name: amazing-fawn-971
run_uuid: eadb7132644b4d5bba45bdf5a2104b09
source_name: ''
source_type: 4
source_version: ''
start_time: 1749067960634
status: 1
tags: []
user_id: reema
