artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/88331e8efb5441f7a13adc73efe11fbf/artifacts
end_time: 1745441956247
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: 88331e8efb5441f7a13adc73efe11fbf
run_name: fortunate-sloth-817
run_uuid: 88331e8efb5441f7a13adc73efe11fbf
source_name: ''
source_type: 4
source_version: ''
start_time: 1745441955274
status: 4
tags: []
user_id: reema
