digest: c83b9fac
name: dataset
profile: '{"num_rows": 120, "num_elements": 480}'
schema: '{"mlflow_colspec": [{"type": "double", "name": "SepalLengthCm", "required":
  true}, {"type": "double", "name": "SepalWidthCm", "required": true}, {"type": "double",
  "name": "PetalLengthCm", "required": true}, {"type": "double", "name": "PetalWidthCm",
  "required": true}]}'
source: '{"tags": {"mlflow.user": "reema", "mlflow.source.name": "C:\\Users\\reema\\AppData\\Roaming\\Python\\Python311\\site-packages\\ipykernel_launcher.py",
  "mlflow.source.type": "LOCAL"}}'
source_type: code
