artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/342590679759320784/9eb251413cca4f2e8f6ef1dd0cda7a33/artifacts
end_time: 1746709186748
entry_point_name: ''
experiment_id: '342590679759320784'
lifecycle_stage: active
run_id: 9eb251413cca4f2e8f6ef1dd0cda7a33
run_name: gregarious-mule-687
run_uuid: 9eb251413cca4f2e8f6ef1dd0cda7a33
source_name: ''
source_type: 4
source_version: ''
start_time: 1746709154584
status: 4
tags: []
user_id: reema
