artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/756198011358616989/cb33f4b0bf2c46599ab9f1232bd4f6f2/artifacts
end_time: null
entry_point_name: ''
experiment_id: '756198011358616989'
lifecycle_stage: active
run_id: cb33f4b0bf2c46599ab9f1232bd4f6f2
run_name: omniscient-wasp-373
run_uuid: cb33f4b0bf2c46599ab9f1232bd4f6f2
source_name: ''
source_type: 4
source_version: ''
start_time: 1750081351659
status: 1
tags: []
user_id: reema
