artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/432125278223922573/0def8fd154874bd0bbcfce4496e263a8/artifacts
end_time: null
entry_point_name: ''
experiment_id: '432125278223922573'
lifecycle_stage: active
run_id: 0def8fd154874bd0bbcfce4496e263a8
run_name: omniscient-colt-216
run_uuid: 0def8fd154874bd0bbcfce4496e263a8
source_name: ''
source_type: 4
source_version: ''
start_time: 1747408295755
status: 1
tags: []
user_id: reema
