artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/730849843658119617/94e97b107b5c437ebdf924cbaff53e5b/artifacts
end_time: 1746644103557
entry_point_name: ''
experiment_id: '730849843658119617'
lifecycle_stage: active
run_id: 94e97b107b5c437ebdf924cbaff53e5b
run_name: hilarious-snipe-988
run_uuid: 94e97b107b5c437ebdf924cbaff53e5b
source_name: ''
source_type: 4
source_version: ''
start_time: 1746644079149
status: 4
tags: []
user_id: reema
