artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/810866651223894986/0937e70a4ea74ebfbda6605e55e4c970/artifacts
end_time: null
entry_point_name: ''
experiment_id: '810866651223894986'
lifecycle_stage: active
run_id: 0937e70a4ea74ebfbda6605e55e4c970
run_name: calm-bee-470
run_uuid: 0937e70a4ea74ebfbda6605e55e4c970
source_name: ''
source_type: 4
source_version: ''
start_time: 1749285404731
status: 1
tags: []
user_id: reema
