artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/256385050532529731/74063de5c7b447a2bec6aaffa6c8dc70/artifacts
end_time: 1746651573002
entry_point_name: ''
experiment_id: '256385050532529731'
lifecycle_stage: active
run_id: 74063de5c7b447a2bec6aaffa6c8dc70
run_name: fun-hawk-560
run_uuid: 74063de5c7b447a2bec6aaffa6c8dc70
source_name: ''
source_type: 4
source_version: ''
start_time: 1746651532321
status: 3
tags: []
user_id: reema
