artifact_uri: file:///C:/Users/reema/REPO/notebooks/RQ_notebooks/mlrunlogs/mlflow.db/615223710259862608/71ae51eca61c469ca2aa81bd9b1bf9eb/artifacts
end_time: 1745439802153
entry_point_name: ''
experiment_id: '615223710259862608'
lifecycle_stage: active
run_id: 71ae51eca61c469ca2aa81bd9b1bf9eb
run_name: luxuriant-dove-341
run_uuid: 71ae51eca61c469ca2aa81bd9b1bf9eb
source_name: ''
source_type: 4
source_version: ''
start_time: 1745439801075
status: 4
tags: []
user_id: reema
